# Site wide configuration

title: LogicalDK
locale: en_US
description: These are my blogs and content. I love to write about JAVA, MongoDB, JavaScript, Groovy & Grails
logo: site-logo.png
search: true
url: http://blogs.logicaldk.in

# Jekyll configuration

permalink:   /:categories/:year/:month/:day/:title
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-paginate

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

paginate: 6

# Site owner
owner:
  name: Dhanendra Kumar
  avatar: bio-photo.jpg
  email: dhanendrakumarkht@gmail.com
  contact-number: +91-9999264661, +91-8527971602
  disqus-shortname: logicaldk
  twitter: logical_dk
  facebook: dhanendrakumar
  github: dhanendra-kumar
  stackexchange: http://stackoverflow.com/users/3985379/dhanendra-kumar
  linkedin: dhanendra-kumar-2ab57b91
  instagram: _dhanendra
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: Dhanendra
    analytics: UA-99247160-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:

theme: jekyll-theme-leap-day